language: php 

php:
  - 7.1

services:
  - docker

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - "ci-scripts/setup_drupal.sh"
  - "ci-scripts/setup_zalenium.sh"
  - "ci-scripts/setup_webdriverio.sh"

script:
  - "ci-scripts/run_webdriverio.sh"
